### ISSUE TITLE
EPG not working

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [AlexanderSofronov/iptv.example#10]
Hi 

EPG is not working i have tested enabling the EPG url on main activity and also on the m3u channels list

on the m3u channel list i was able to load channels list, logo channel list ok

but no EPG working yet

also how can i add bar on left menu to import manually URL m3u list? via browser of app?

**Comment by AlexanderSofronov** [comment]
Can you please share your playlist and EPG for testing? If you don't want to publish here you can send them to iptvap@gmail.com.

What about left menu to import playlist manually, this feature is missing in IPTV Core and available in IPTV and IPTV Pro apps.

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hiya 

sorry for late reply, epg is working fine was just a configuration file issue..
everything is working ok
