### ISSUE TITLE
EPG on main channel MENU BAR with channel icon for STB devices

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [AlexanderSofronov/iptv.example#11]
Hiya 

i have been testing it on my mx9 stb, and i would like to add the EPG and channel icon on the main menu channel bar on the bottom part of the  TV screen is this possible to customize on the player code

something similar to this here below, specific page for EPG showing like this menu, and also on the channel event like this

http://blog.listaiptvbrasil.com.br/wp-content/uploads/2017/12/Perfect-Player-IPTV.png

https://1.bp.blogspot.com/-EugoBVDZrKw/WBs-KWyBVbI/AAAAAAAAGdQ/k_r0Iz2uZoYun84NYD6zvQn007jl0PV2QCLcB/s1600/unnamed.png

https://http2.mlstatic.com/xiaomi-mi-tv-box-android-60-4k-iptv-app-filmes-D_NQ_NP_662685-MLB27695028503_072018-F.jpg

**Comment by AlexanderSofronov** [comment]
We released IPTV Core 4.2.2 recently, it has internal video player and can show channel icon and EPG over the video screen

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hello thanks do i need to update anything on the source code to fetch the new player, or this is done automatically?

**Comment by AlbertEinsteinGlitchPoint** [comment]
Also quick question

i am adapting player and i want to remove the ads from player, if i buy comercial version , os player core wil adds disappear? do all users fro my app need to buy also the player license fee? or can i embedd my license details inside player?
