### ISSUE TITLE
IPTV Core APK into Android studio

### ISSUE THREAD

**Issue by fyahb** [AlexanderSofronov/iptv.example#3]
How can i add IPTV core apk into my android studio app. So that it downloads with my app.
Instead of getting the message IPTV Core not installed, Please install \"IPTV Core\" app from Google Play

**Comment by AlexanderSofronov** [comment]
There is no way to compile your project with IPTV Core apk, IPTV Core is separate app and should be installed separately.

**Comment by nadir2316** [comment]
Is it possible to help me to create an application that allows access to it via the username and password to connect it to the panel xtream

**Comment by AlexanderSofronov** [comment]
@nadir2316, your question is not related to the topic of this issue. I'm closing this.

**Comment by spookey2008** [comment]
Anyway of removing the ads Thanks

**Comment by hunsel** [comment]
Hi sir/madam.

can you please help me.i am reseller of iptv.i have a good number of customers.
i wanted to create my own iptv application.so my customers can easily get and watch my channels...
i have installed android studio into my pc.please help me how to get started.thank you

**Comment by fyahb** [comment]
I have tried creating a app. But it doesn't have the functions I need. I
paid about $600 for my app. It has epg (TV Guide), It shows billing info,
can submit tickets, can pay Bill thru app.
Iptv charters is what I use
