### ISSUE TITLE
Multiple Playlist URLs

### ISSUE THREAD

**Issue by rtirak** [AlexanderSofronov/iptv.example#4]
Is it possible to have 2 playlist URLs and 2 EPG urls in the same app?

**Comment by AlexanderSofronov** [comment]
The app doesn't support 2 playlist URLs, but it supports 2 EPG URLs. You can set multiple EPG URLs separated by commas via playlist "url-tvg" or via Intent API.

**Comment by rtirak** [comment]
Thanks for the response/info. I was wondering if you had an email address or a Skype name I might be able to contact you on with another question/advice?

**Comment by AlexanderSofronov** [comment]
You can send me email to iptvap@gmail.com
