### ISSUE TITLE
Option to remove "All Channels" category

### ISSUE THREAD

**Issue by slim223** [AlexanderSofronov/iptv.example#7]
Hi, is it possible to have the option to remove the "All Channels" category from menubar.

**Comment by techker** [comment]
seems like it is the core driving the skin. would need to find source of the iptv core to be able to change it..i wish i can find it..lol

**Comment by AlexanderSofronov** [comment]
This option was implemented in IPTV Core 3.9.4. Please use the following intent extra to hide "All Channels" tab: intent.putExtra("hide_all_channels_tab", true)
