### ISSUE TITLE
How to customize user-agent in android vlc sdk

### ISSUE THREAD

**Issue by willowTank** [AlexanderSofronov/iptv.example#8]
I used vlc palyer for IPTV apk
I am going to change user-agent for this player
but when I customize user-agent, I got "my_custom_user_agent LibVLC/3.00-git" too
How can i delete this strings : "LibVLC/3.00-git"
Pls let me know

**Comment by AlexanderSofronov** [comment]
This question is related to VLC, not to IPTV Core
